### PR TITLE
[RPC] Expand vote

### PR DESCRIPTION
**Pull request by kjunu**

### CODE REVIEW

**Comment by graup** [comment]
Are these unique? Maybe use a different name like `name` or `identifier`. A title is usually a human-readable, non-unique string.

**Comment by ashen1dev** [comment]
Can you explain the usage of new field? Id for candidates? or for further feature like DAO proposal?

**Comment by kjunu** [comment]
It will be used to let users know which elections they voted for
(ex : "bp" - [bp1,bp2,bp3] , "num of bp" - 23, "bp" and "num of bp" is title)
maybe "name" is more proper naming then "title".

**Comment by kjunu** [comment]
It was quick and dirty way for basic usage and will be improved soon.
In this version, server RPC will return data like below.
[
{"title":"voteBP","amount":"10","candidate":"peer1"},{"title":"voteBP","amount":"10","candidate":"peer2"},
{"title":"numBP","amount":"10","candidate":"23"}
]

**Comment by kjunu** [comment]
I remove the "title" and add new API to show result of vote

**Comment by graup** [comment]
Looks good. Could you add the changes to the [Changelog](https://github.com/aergoio/aergo-protobuf/blob/master/CHANGELOG.md)?

/edit: Actually I can also do it after we merge this, seems the Changelog needs some fixing anyways.

**Pull request merged**
